name: otel_cloud_functions
description: OpenTelemetry instrumentation for `package:cloud_functions`.
  Wraps HttpsCallable.call with `rpc.*` semconv spans for callable
  Firebase Functions.
version: 0.1.0
repository: https://github.com/dartastic/otel_cloud_functions
homepage: https://dartastic.io

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  cloud_functions: ">=5.0.0 <7.0.0"
  dartastic_opentelemetry: ^1.1.0-beta.12
  dartastic_opentelemetry_api: ^1.0.0-rc.1
  flutter:
    sdk: flutter

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
  pub_semver: ^2.0.0
  pubspec_parse: ^1.5.0
